AWSTemplateFormatVersion: 2010-09-09
Description: Create S3 Bucket

Parameters:
#-------------------------------------------------------------------
# Base Name
#-------------------------------------------------------------------
  Namebase:
    Type: String
    Default: "cfn-deploy"

Resources: 
#-------------------------------------------------------------------
# S3 Bucket
#-------------------------------------------------------------------
#S3 Bucket
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join
        - '-'
        - - !Sub "${Namebase}"
          - 's3-owner'
          - !Ref AWS::AccountId
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: 'aws:kms' 
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags: 
        - Key: Name
          Value: !Sub "${Namebase}"

Outputs:
#-------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------
#S3 Bucket
  S3Bucket:
    Value: !Ref S3Bucket
    Export:
      Name: S3BucketName
