version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.4.0
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
  cfn-deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup:
          role_arn: arn:aws:iam::713881797072:role/cfn-deploy-OIDC-role
          role_session_name: cfn-deploy-OIDC
          region: ${AWS_REGION}
      - run:
          name: debug
          command: aws sts get-caller-identity

workflows:
  raisetech:
    jobs:
      - cfn-lint
      - cfn-deploy:
          context: AWS
