version: 2.1
orbs:
  python: circleci/python@2.0.3
  aws-cli: circleci/aws-cli@5.4.0
jobs:
  cfn-lint:
    executor: python/default
    steps:
      - checkout
      - run: pip install cfn-lint
      - run:
          name: run cfn-lint
          command: |
            cfn-lint -i W3002 -t cloudformation/*.yml
  cfn-deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup:
          role_arn: arn:aws:iam::713881797072:role/cfn-deploy-OIDC-role
          region: ap-northeast-1
      - run:
          name: run cfn-deploy
          command: |
            aws cloudformation deploy --template-file ./cloudformation/1_VPC.yml --stack-name cfn-deploy-VPC --region ap-northeast-1 --no-fail-on-empty-changeset 
            aws cloudformation deploy --template-file ./cloudformation/2_Sec.yml --stack-name cfn-deploy-Sec --region ap-northeast-1 --no-fail-on-empty-changeset 
            aws cloudformation deploy --template-file ./cloudformation/3_S3.yml --stack-name cfn-deploy-S3 --region ap-northeast-1 --no-fail-on-empty-changeset 
            aws cloudformation deploy --template-file ./cloudformation/4_EC2.yml --stack-name cfn-deploy-EC2 --region ap-northeast-1 --no-fail-on-empty-changeset 
            aws cloudformation deploy --template-file ./cloudformation/5_ALB.yml --stack-name cfn-deploy-ALB --region ap-northeast-1 --no-fail-on-empty-changeset 
            aws cloudformation deploy --template-file ./cloudformation/6_RDS.yml --stack-name cfn-deploy-RDS --region ap-northeast-1 --no-fail-on-empty-changeset 
   
workflows:
  raisetech:
    jobs:
      - cfn-lint
      - cfn-deploy:
          context: AWS
 
