---
# tasks file for mysql installation
- name: Uninstall mariadb
  become: true
  ansible.builtin.yum:
    name: mariadb-libs
    state: absent

- name: Download mysql-community repository
  ansible.builtin.command:
    chdir: /home/ec2-user/work
    cmd: wget https://dev.mysql.com/get/mysql84-community-release-el7-1.noarch.rpm
    creates: ~/work/mysql84-community-release-el7-1.noarch.rpm"

- name: Install mysql-community repository
  become: true
  ansible.builtin.yum:
    name: "/home/ec2-user/work/mysql84-community-release-el7-1.noarch.rpm"
    state: present

- name: Install mysql-community-client
  become: true
  ansible.builtin.yum:
    name: mysql-community-client
    state: present
