- name: Initial setup
  user: ec2-user
  hosts: all
  tasks: 
    - name: Change the timezone
      community.general.timezone:
        name: Asia/Tokyo

    - name: Create a working directory
      ansible.builtin.file:
        path: /home/ec2-user/work
        state: directory

    - name: Install a package group
      become: true
      ansible.builtin.yum:
        name: '@Development tools'
        state: present

    - name: Install packages
      become: true
      ansible.builtin.yum:
        name:
          - git
          - kernel-headers
          - bzip2
          - curl
          - glibc-devel
          - libffi-devel
          - readline-devel
          - zlib-devel
          - gdbm-devel
          - ncurses-devel
        state: present

    - name: Uninstall mariadb
      become: true
      ansible.builtin.yum:
        name: mariadb-libs
        state: absent

    - name: Download mysql-community repository
      ansible.builtin.command:
        chdir: /home/ec2-user/work
        cmd: wget https://dev.mysql.com/get/mysql84-community-release-el7-1.noarch.rpm
        creates: ~/work/mysql84-community-release-el7-1.noarch.rpm"

    - name: Install mysql-community repository
      become: true
      ansible.builtin.yum:
        name: "/home/ec2-user/work/mysql84-community-release-el7-1.noarch.rpm"
        state: present

    - name: Install mysql-community-client
      become: true
      ansible.builtin.yum:
        name: mysql-community-client
        state: present
